name: HA/mqtt2pg
windows:
  2:
    name: run
    command: |
      # export MQTT_URL=mqtt://hab
      # export PG_URL=postgresql://mqtt2pg:SECRET@hab:5432/hab
      export MQTT_USER='' MQTT_PASSWORD=''
      export PGDATABASE=hab
      # export PG_URL=postgresql://localhost/hab
      node mqtt2pg run --logging-config-file dev-log-conf.edn
      #
  3:
    name: repl
    command: |
      sleep 30
      export PATH="./node_modules/.bin:${PATH}"
      npx shadow-cljs cljs-repl service
  7:
    name: build
    command: |
      export PATH="./node_modules/.bin:${PATH}"
      # shadow-cljs release application
      npx shadow-cljs watch service
  8:
    name: deploy
    command: |
      source py3-venv/bin/activate
      # export PG_PASSWORD='' MQTT_PASSWORD=''
      # ansible-playbook -i ~/Programming/SystemEngineering/my-servers_ansible/hosts_home.yml -l hab deploy/deploy_play.yml -e "pg_password=$PG_PASSWORD" -e "mqtt_password=$MQTT_PASSWORD"
