name: HA/mqtt2pg
windows:
  2:
    name: run
    command: |
      # export MQTT_URL=mqtt://hab
      # export PG_URL=postgresql://mqtt2pg:SECRET@hab:5432/hab
      export MQTT_USER='' MQTT_PASSWORD=''
      export PGDATABASE=hab
      # export PG_URL=postgresql://localhost/hab
      sleep 30
      ./mqtt2pg run --logging-config-file dev-log-conf.edn
      #
  3:
    name: repl
    command: |
      sleep 30
      export PATH="./node_modules/.bin:${PATH}"
      npx shadow-cljs cljs-repl service
  7:
    name: build|watch
    command: |
      # ./bin/build shadow-cljs release application
      ./bin/watch
  8:
    name: deploy
    command: |
      # open session to Bitwarden!
      # ./bin/deploy2hab2hab
