- name: install apt dependencies
  apt:
    name: "{{ packages }}"
    update_cache: yes
    cache_valid_time: 3600
  vars: 
    packages: [openjdk-11-jdk]
  tags: [apt, internet]


- name: create user
  user:
    name: "{{user}}"
    system: yes
    shell: /bin/bash
  tags: [user]

- file:
    path: "{{workingdir}}"
    state: absent
  tags: [workingdir]
  when: clean_workingdir 

- file:
    path: "{{workingdir}}"
    state: directory
    recurse: yes
    owner: mqtt2pg
  tags: [workingdir]


### dependencies ###############################################################

- name: copy files
  copy:
    src: '{{playbook_dir}}/../{{item}}'
    dest: '{{workingdir}}/{{item}}'
    owner: '{{user}}'
    mode: u=rw,go=r
  with_items: 
  - src/
  - package-lock.json
  - package.json
  - shadow-cljs.edn
  tags: [copy]

- name: install npm stuff
  become_user: '{{user}}'
  become: yes
  become_flags: -i
  become_method: sudo
  shell: |
    cd {{workingdir}}
    npm install
  args:
    executable: /bin/bash
  tags: [npm]


### application  ###############################################################

- name: build application
  #delegate_to: localhost
  become_user: "{{user}}"
  become: yes
  become_flags: -i
  become_method: sudo
  shell: |
    #!/bin/bash
    set -euxo
    cd {{workingdir}}
    ./node_modules/.bin/shadow-cljs release application 
    chmod a+x mqtt2pg
  tags: [build, application]


### service ####################################################################

- name: install systemd service files
  template:
    src: '{{item}}'
    dest: '/etc/systemd/system/{{item}}'
    mode: 0644
  with_items:
    - mqtt2pg.service
  tags: [service]

- name: reload systemctl
  command: systemctl daemon-reload
  changed_when: false
  tags: [service]

- name: resetart service
  service:
    name: mqtt2pg.service
    state: restarted
    enabled: yes
  tags: [service]
