- include_tasks:
    file: install_nodejs.yml
    apply: {tags: install_nodejs}
  tags: install_nodejs

- include_tasks:
    file: build.yml
    apply: {tags: build}
  tags: build

- include_tasks:
    file: install.yml
    apply: {tags: install}
  tags: install

- include_tasks:
    file: service.yml
    apply: {tags: service}
  tags: service

